syntax = "proto2";

package apollo.guardian;

import "modules/collision_guardian/proto/collision_guardian.proto";

message GuardianConf {
  optional bool guardian_enable = 1 [default = false];
  optional double guardian_cmd_emergency_stop_percentage = 2 [default = 50];
  optional double guardian_cmd_soft_stop_percentage = 3 [default = 25];
  optional bool collision_guardian_enable = 4 [default = false];
  optional string collision_risk_topic = 5
      [default = "/apollo/collision_guardian/risk"];
  optional double collision_risk_timeout_sec = 6 [default = 0.5];
  optional double collision_hard_stop_max_speed_mps = 7 [default = 2.0];
  optional bool collision_require_complete_auto_drive = 8 [default = true];
  repeated apollo.collision_guardian.UseCase collision_allowed_use_case = 9;
}
