blank_issues_enabled: false
contact_links:
  - name: 'Community Forum'
    url: 'https://github.com/orgs/wheelos/discussions'
    about: 'Ask usage questions and discuss ideas with the WheelOS community.'
