[Unit]
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=
# Add -m to ensure log output is to the systemd journal
ExecStart=/usr/sbin/ptp4l -f /etc/linuxptp/ptp4l.conf -i eth0 -m
