package(
    default_visibility = ["//visibility:public"],
)

config_setting(
    name = "use_gpu",
    define_values = {
        "USE_GPU": "true",
    },
)

config_setting(
    name = "with_teleop",
    define_values = {
        "WITH_TELEOP": "true",
    },
)
