--flagfile=/apollo/modules/common/data/global_flagfile.txt

--local_map_name=local_map
--enable_lidar_localization=true
--if_utm_zone_id_from_folder=true
--local_utm_zone_id=10

--lidar_topic=/apollo/sensor/hesai40/compensator/PointCloud2
--broadcast_tf_frame_id=map
--broadcast_tf_child_frame_id=base_link

--lidar_height_file=/apollo/modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
--lidar_height_default=1.80

--ndt_map_dir=ndt_map
--online_resolution=2.0
--ndt_max_iterations=10
--ndt_target_resolution=1.0
--ndt_line_search_step_size=0.1
--ndt_transformation_epsilon=0.01
--ndt_filter_size_x=48
--ndt_filter_size_y=48
--ndt_bad_score_count_threshold=10
--ndt_warnning_ndt_score=1.0
--ndt_error_ndt_score=2.0
